### ISSUE TITLE
Create new theme

### ISSUE THREAD

**Issue by xavierfuentes** [xavifuefer/pailan#13]
- [x] Install Linexon theme
- [x] Research customisation
- [ ] Customise markup and style for the landing page
- [x] Customise markup and style for sign in page
- [x] Customise markup and style for forgot the password
- [x] Customise markup and style for sign up page
- [x] Customise markup and style for services list page
- [x] Customise markup and style for new service page
- [x] Customise markup and style for user profile

**Comment by DavidPombar** [comment]
Tete, cosas varias:
- en la cabecera hay una imagen de Linexon que deberíamos cambiar por un H1 Pailan.io, pero hay dos opciones de color que no se como reproducir en html/css
- hay que hacer dos "capturas" para poner en los mockups. En la primera una pantalla con iconos de proveedores es suficiente, la segunda cualquier pollada de gráfica y poner una banda por encima que ponga "coming soon" ;)
- no tengo puta idea de como crear una nueva página estática, ¿creo un fichero?, así meto términos y condiciones y textos legales....

OJO, La versión sobre la que esto trabajando, rama feature/013-create-new-theme, no tiene el menú de iconos que me enseñaste.

Cuando tengas algo más avanzado el back le puedo meter yo lo de analytics.

**Comment by xavierfuentes** [comment]
@DavidPombar 

* la imagen de fondo para la landing ya está arreglada. El problema es que la ruta debe ser relativa a la carpeta `public`, esa es la root publica así que la ruta correcta era: `/images/cabecera.jpEg` y no `../images/cabecera.jpg`. Aunque el mayor problema era que habías escrito `.jpg` y la imagen tiene extensión `.jpEg` :P
* la imagen de Linexon la tenemos que reemplazar con otra imagen con el texto que queramos, va a ser mucho más rápido que cambiar el texto de color con JS al hacer scroll.
* no había hecho push de los cambios en la página add service, porque no estaba acabada la tarea, ahora ya sí.
* para crear otra página solo tienes que crear otro archivo `.pug` poner el contenido que quieras. Puedes usar el archivo `views/services/add.pug` como plantilla. La vista por si sola no va a funcionar. necesitas crear un nuevo controller (coge el `controllers/home.js` como ejemplo) y añadir la ruta que quieras al archivo `app.js`. De la linea 127 a la 147 tienes varios ejemplos de rutas. Fíjate que la estructura es `app.VERBO('/NOMBRE_URL', controlador.metodo)`.

Tareas pendientes:
* Capturas para la landing
* corregir textos en ingles de la landing

**Comment by xavierfuentes** [comment]
[Aqui](https://pugjs.org/language/inheritance.html) puedes encontrar documentacion sobre JADE/PUG 
[Aqui](http://getbootstrap.com/docs/4.0/layout/grid/) sobre Bootstrap 4

**Comment by xavierfuentes** [comment]
por cierto, cada vez que hagas un cambio en un archivo NO necesitas hacer `docker-compose build web` con ejecutar `docker-compose up web` deberia bastar. La proxima vez que hablemos te pondre un mongo local y podras hacerlo mas rapido sin docker
