### ISSUE TITLE
Listado de servicios disponibles

### ISSUE THREAD

**Issue by DavidPombar** [xavifuefer/pailan#2]
Lista de servicios disponibles:
* nombre
* logo
* url base

**Comment by DavidPombar** [comment]
@xavifuefer pq mueves esto a review si está sin hacer? :(

**Comment by xavierfuentes** [comment]
porque no entendí lo que significaba :D

**Comment by DavidPombar** [comment]
jajajjajajaja que mamón, y lo que no entiendes lo cierras?, pues cierra cataluña! :P

**Comment by xavierfuentes** [comment]
cuando lo he leido por segunda vez he entendido que era los "por defecto" no los "custom".

**Comment by xavierfuentes** [comment]
voy a necesitar una lista de proveedores por defecto que queremos usar

**Comment by DavidPombar** [comment]
Creo que podemos meter un campo categoría ya, no debería costar nada y a poco que añadamos facilita mucho:

Hosting & Domains
- Amazon AWS
- Digital Ocean
- Linode
- Pivotal Web Services
- Heroku
- Godaddy
- Namecheap

Marketing & Sales
- Buffer
- Hootsuite
- Intercom
- Mailchimp
- Typeform
- Unbounce
- Olark
- Semrush
- Moz

Dev tools
- Github
- Mandrill
- Papertrail
- Sentry
- Sendgrid
- Travis CI
- Twilio
- New Relic

Support
- Intercom
- Help Scout

Project Management
- Attlasian
- Basecamp
- Taiga
- Asana
- Trello
- Cloudhouse

Payments & Invocing 
- Stripe
- Quaderno
- Braintree
- PayPal
- Recurly
- Chargify
- Quickbooks
- Profitwell
- Baremetrics
- Chartmogul

Others
- Zapier
- Poeditor
- Google Apps
- Slack

@xavifuefer  Si me dices como meter esto en la BBDD nombre, categoria, url e icono los meto yo.

**Comment by DavidPombar** [comment]
[   {     "_id": ObjectId("59e7eba78002e24813c03166"),     "name": "Example Service 1",     "url": "http://www.example-service1.com",     "owner": "default"   },   {     "_id": ObjectId("59e7eba78002e24813c03167"),     "name": "Example Service 2",     "url": "http://www.example-service2.com",     "owner": "default"   },   {     "_id": ObjectId("59e7eba78002e24813c03168"),     "name": "Example Service 3",     "url": "http://www.example-service3.com",     "owner": "default"   } ]

**Comment by DavidPombar** [comment]
Definición actual
const serviceSchema = new mongoose.Schema(   {     name: String,     slug: { type: String, unique: true, index: true },     url: String,     // logo: String,     owner: { type: mongoose.Schema.Types.ObjectId, index: true },     user: String,     password: String,   },   { timestamps: true } );

**Comment by DavidPombar** [comment]
@xavifuefer te los dejo en esta rama https://github.com/xavifuefer/expensit/tree/default-services

**Comment by xavierfuentes** [comment]
@DavidPombar  añadí los servicios a mi branch, así que supongo que podemos cerrar este issue. Por cierto, me puedes confirmar si la repeticion de un servicio era un error?
```
{
  "_id": ObjectId("59e7eba78002e24813c03205"),
  "name": "Chargify",
  "logo": "https://help.chargify.com/img/chargify_large.png",
  "category": "Payments & Invocing",
  "url": "https://app.chargify.com",
  "owner": "default"
}
{
  "_id": ObjectId("59e7eba78002e24813c03205"),
  "name": "Chargify",
  "logo": "https://www.nethelpdesk.com/img/logos/help-desk-software-quickbooks-intuit.png",
  "category": "Payments & Invocing",
  "url": "https://quickbooks.intuit.com",
  "owner": "default"
}
{
  "_id": ObjectId("59e7eba78002e24813c03206"),
  "name": "Quickbooks",
  "logo": "https://www.nethelpdesk.com/img/logos/help-desk-software-quickbooks-intuit.png",
  "category": "Payments & Invocing",
  "url": "https://quickbooks.intuit.com",
  "owner": "default"
}
```

**Comment by DavidPombar** [comment]
@xavifuefer si, la del medio está mal, cepíllatelo

**Comment by xavierfuentes** [comment]
ok. resuelto.
