### ISSUE TITLE
Instalar un Admin

### ISSUE THREAD

**Issue by DavidPombar** [xavifuefer/pailan#4]
Instalar un Admin de Django desde el que acceder a las credenciales de los usuarios y subirles las facturas.

Ej http://djangosuit.com

**Comment by xavierfuentes** [comment]
le he estado dando vueltas a esto y creo que seria mejor tirar por NodeJS dada mi experiencia con Python. Qué opinas?

**Comment by xavierfuentes** [comment]
echar un vistazo a https://github.com/crudlio/crudl
